version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ridesharing
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - config.env
    environment:
      DEBUG: 'True'
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ridesharing
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: '5432'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      PORT: '8080'
      API_KEY: ride_sharing_test_key_123
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: django_secret_key_789xyz123abc
      ALLOWED_HOSTS: localhost,127.0.0.1

volumes:
  postgres_data:
