services:
  - type: web
    name: ride-sharing-backend
    runtime: docker
    region: oregon  
    plan: starter   
    branch: main
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        fromDatabase:
          name: ride-sharing-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ride-sharing-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ride-sharing-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: ride-sharing-db
          property: host
      - key: DB_PORT
        value: "5432"

databases:
  - name: ride-sharing-db
    plan: starter 