# services:
#   - type: web
#     name: ride-sharing-backend
#     runtime: docker
#     region: oregon  
#     plan: starter   
#     branch: main
#     healthCheckPath: /health/
#     envVars:
#       - key: SECRET_KEY
#         generateValue: true
#       - key: DEBUG
#         value: "False"
#       - key: ALLOWED_HOSTS
#         value: ".onrender.com"
#       - key: DATABASE_URL
#         fromDatabase:
#           name: ride-sharing-db
#           property: connectionString
#       - key: PORT
#         value: "8000"

# databases:
#   - name: ride-sharing-db
#     plan: starter 