# Generated by Django 5.0.1 on 2025-03-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_phone_number_driver_rating_driver_status_and_more"),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="destination_latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ride",
            name="destination_longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="drivers.driver",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
