# Generated by Django 5.0.1 on 2025-03-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_ride_destination_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="destination_latitude",
        ),
        migrations.RemoveField(
            model_name="ride",
            name="destination_longitude",
        ),
        migrations.RemoveField(
            model_name="ride",
            name="pickup_latitude",
        ),
        migrations.RemoveField(
            model_name="ride",
            name="pickup_longitude",
        ),
        migrations.AddField(
            model_name="ride",
            name="destination_place",
            field=models.CharField(default="Salaama", max_length=255),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_place",
            field=models.CharField(default="Kampala", max_length=255),
        ),
    ]
