# Generated by Django 5.0.1 on 2025-03-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_remove_ride_destination_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="destination_place",
            field=models.CharField(default="Salaama", max_length=100),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_place",
            field=models.CharField(default="Kampala", max_length=100),
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("vehicle_model", models.CharField(max_length=50)),
                ("vehicle_plate", models.CharField(max_length=20)),
                ("current_location", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("status", models.CharField(default="available", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_driver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rides.driver",
            ),
        ),
    ]
