# Generated by Django 5.0.1 on 2025-03-18 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_alter_driver_user"),
        ("rides", "0004_alter_ride_destination_place_alter_ride_pickup_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drivers.driver",
            ),
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
    ]
