# Generated by Django 5.0.1 on 2025-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_alter_ride_driver_delete_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="rider",
        ),
        migrations.AddField(
            model_name="ride",
            name="rider_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="destination_place",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_place",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(default="requested", max_length=20),
        ),
    ]
