# Generated by Django 5.0.1 on 2025-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_remove_ride_rider_ride_rider_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="rider_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
