# Generated by Django 5.0.1 on 2025-03-18 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
        migrations.AddField(
            model_name="driver",
            name="rating",
            field=models.FloatField(
                default=5.0,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("busy", "Busy"),
                    ("offline", "Offline"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_model",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle_plate",
            field=models.CharField(default="", max_length=20),
        ),
    ]
