# Generated by Django 5.0.1 on 2025-03-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_phone_number_driver_rating_driver_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="longitude",
        ),
        migrations.AddField(
            model_name="driver",
            name="current_location",
            field=models.CharField(default="Kampala", max_length=255),
        ),
    ]
